# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-13 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(help_text='Your comment here', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productphotos',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
    ]
