# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180313_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Package')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='package',
        ),
    ]
