# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180314_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagePhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Package')),
            ],
        ),
    ]
