# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180314_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(max_length=70),
        ),
    ]
