# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_package_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='main_photo',
            field=models.FileField(upload_to=''),
        ),
    ]
