# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180316_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='short_description',
            field=models.CharField(default='Haha', max_length=70),
        ),
    ]
