# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_package_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='short_description',
            field=models.CharField(max_length=70),
        ),
    ]
