# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180316_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.FileField(default='main/images/Messi.png', upload_to=''),
        ),
    ]
