# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_hotnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='discount_rate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='discounted_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
