# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20180319_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.FileField(default='media/Messi.png', upload_to=''),
        ),
    ]
