# Generated by Django 2.0.3 on 2018-04-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20180325_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='amount_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
