# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='bhd_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='jod_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='kwd_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='lbp_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='omr_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='qar_price',
            field=models.FloatField(default=0),
        ),
    ]
